/*
 * generated by Xtext
 */
package org.xtext.example.task1;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class LangExampleRuntimeModule extends org.xtext.example.task1.AbstractLangExampleRuntimeModule {

}
