/*
 * generated by Xtext
 */
package org.xtext.example.task1.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class LangExampleUiModule extends org.xtext.example.task1.ui.AbstractLangExampleUiModule {
	public LangExampleUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
