/*
* generated by Xtext
*/
package org.xtext.example.task1.ui.contentassist;

import org.xtext.example.task1.ui.contentassist.AbstractLangExampleProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class LangExampleProposalProvider extends AbstractLangExampleProposalProvider {

}
