/*
* generated by Xtext
*/
package org.xtext.example.task1.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.task1.services.LangExampleGrammarAccess;

public class LangExampleParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private LangExampleGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.example.task1.parser.antlr.internal.InternalLangExampleParser createParser(XtextTokenStream stream) {
		return new org.xtext.example.task1.parser.antlr.internal.InternalLangExampleParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public LangExampleGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(LangExampleGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
