/*
 * generated by Xtext
 */
package org.xtext.example.task1.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.task1.ui.internal.LangExampleActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LangExampleExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LangExampleActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LangExampleActivator.getInstance().getInjector(LangExampleActivator.ORG_XTEXT_EXAMPLE_TASK1_LANGEXAMPLE);
	}
	
}
